### ISSUE TITLE
Bugs in README options

### ISSUE THREAD

**Issue by vinylroads** [dcdeiv/simpler-sidebar#14]
Hi, i like your plugin.

However, i don’t know how to change the mask color or to set it to false. In documentation, i see i can use :
```javascript
$.fn.simplerSidebar.mask.display = false;
```
But i still see the mask.

Here is my code :
```javascript
$('#sidebar').simplerSidebar({
    opener: '#toggle-sidebar',
    sidebar: {
      align: 'left', //or 'right' - This option can be ignored, the sidebar will automatically align to right.
      width: 300, //You can ignore this option, the sidebar will automatically size itself to 300px.
      closingLinks: '.bt_close' // If you ignore this option, the plugin will look for all links and this can be buggy. Choose a class for every object inside the sidebar that once clicked will close the sidebar.
    }
  });
  
  $( '#sidebar' ).fn.simplerSidebar.mask.display = false;
  $( '#sidebar' ).simplerSidebar();

```

Is there something wrong ?

**Comment by dcdeiv** [comment]
Thank you for pointing that! I've just realized that the options in the README are not updated!
Let's go point by point:

***

If you want to hide the mask div you can do it in two ways:

1) You can use the shortcut just before the main plugin, and the right way to do it is in this way:

```javascript
$.fn.simplerSidebar.settings.mask.display = false;

$('#sidebar').simplerSidebar({
    opener: '#toggle-sidebar',
    top: 60, //this is a mere example, but you should add this option when you hide the mask to fully show the top navbar and the icon that opens and close the sidebar.
    sidebar: {
        align: 'left',
        width: 300,
        closingLinks: '.bt_close'
    }
});
```
You should not call again the `$('#sidebar')` function unless you use a second sidebar. If you want to override an option use this base API instead: `$.fn.simplerSidebar.settings`.


2) The second way you can hide the mask, is with the same option but in the plugin:

```javascirpt
$('#sidebar').simplerSidebar({
    opener: '#toggle-sidebar',
    top: 60, //this is a mere example, but you should add this option when you hide the mask to fully show the top navbar and the icon that opens and close the sidebar.
    sidebar: {
        align: 'left',
        width: 300,
        closingLinks: '.bt_close'
    },
    mask: {
        display: false
    }
});
```

***

If you want to tweak the mask by changing it's style you can do it in three ways:

1) You can change it in your CSS file by calling it in this way. Be sure to match the plugin name (see `attr` option).

```css
[data-simplersidebar="mask"] {
    background-color: black;
    opacity: 0.5;
    filter: Alpha(opacity=50);
}
```
This three options are set in the plugin so it is better to tweak them in the plugin itself (See point 2 below). The other style options are free to be tweaked in your CSS.

2) You can change it in the plugin by calling its option:

```javascript
$.fn.simplerSidebar.settings.mask.css.backgroundColor = 'black';
$.fn.simplerSidebar.settings.mask.css.opacity = 0.5;
$.fn.simplerSidebar.settings.mask.css.filter = 'Alpha(opacity=50)';
```

or

```javascript
$.fn.simplerSidebar.settings.mask.css = {
    backgroundColor: 'red',
    opacity: 0.5,
    filter: 'Alpha(opacity=50)'
}
```

***

If you have any further question, please, add a comment below!
