### ISSUE TITLE
jQuery 2.x compatibility

### ISSUE THREAD

**Issue by michellaurent** [dcdeiv/simpler-sidebar#8]
Is this sidebar compatible with jQuery 2.1.4 ?

**Comment by dcdeiv** [comment]
Have you tried? Let me know.

**Comment by michellaurent** [comment]
I think it works. I replaced 
```<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>``` with 
```<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>```in the test file and it looks like it works.

**Comment by dcdeiv** [comment]
I have never checked if it works, but I you say that It seems to work just fine I guess it is ok! I've never checked if jquery#2 would be fine because of its backport compatibility! Let me know if you find some bugs with jquery#2 and I will try to fix it!
